[phases.build]
cmds = [
  "ls -la resources/views",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache || true",
  "php artisan migrate:fresh --force --seed",
  "php artisan storage:link || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
